# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17krJKhc-zCGrola3Klkk7pTsFtiAufuo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv(r"/content/archive.zip")

data.head(10)
data.info()

from sklearn.preprocessing import MinMaxScaler
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = MinMaxScaler()
df_normalized = data.copy()
df_normalized[numeric_cols] = scaler.fit_transform(data[numeric_cols])
print(df_normalized[numeric_cols].head())

from sklearn.preprocessing import RobustScaler
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = RobustScaler()
df_scaled = data.copy()
df_scaled[numeric_cols] = scaler.fit_transform(data[numeric_cols])
print(df_scaled[numeric_cols].head())

from sklearn.preprocessing import StandardScaler
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
df_standardized = data.copy()
df_standardized[numeric_cols] = scaler.fit_transform(data[numeric_cols])
print(df_standardized[numeric_cols].head())
