# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPDwCo4t-fa90duQjrXIHCUUzoQxggUl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv(r"/content/archive.zip")

data.head(10)
data.info()

!pip install ydata-profiling

from ydata_profiling import ProfileReport
prof = ProfileReport(data)
prof.to_file(output_file='EDA.html')
from IPython.core.display import display, HTML
display(HTML(prof.to_html()))