# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17krJKhc-zCGrola3Klkk7pTsFtiAufuo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv(r"/content/archive.zip")

data.head(10)
data.info()

from sklearn.preprocessing import MinMaxScaler
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = MinMaxScaler()
df_normalized = data.copy()
df_normalized[numeric_cols] = scaler.fit_transform(data[numeric_cols])
print(df_normalized[numeric_cols].head())

from sklearn.preprocessing import RobustScaler
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = RobustScaler()
df_scaled = data.copy()
df_scaled[numeric_cols] = scaler.fit_transform(data[numeric_cols])
print(df_scaled[numeric_cols].head())

from sklearn.preprocessing import StandardScaler
numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
df_standardized = data.copy()
df_standardized[numeric_cols] = scaler.fit_transform(data[numeric_cols])
print(df_standardized[numeric_cols].head())

import pandas as pd
iris = pd.read_csv("/content/IRIS (1).csv")

x = iris.iloc[:,:-1].values
y = iris.iloc[:, -1].values

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters=3)
y_pred = hc.fit_predict(x)

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x[y_pred == 0,0], x[y_pred == 0,1], x[y_pred == 0,2], s=50, c='red', label='Cluster 1')
ax.scatter(x[y_pred == 1,0], x[y_pred == 1,1], x[y_pred == 1,2], s=50, c='green', label='Cluster 2')
ax.scatter(x[y_pred == 2,0], x[y_pred == 2,1], x[y_pred == 2,2], s=50, c='blue', label='Cluster 3')

plt.legend()
plt.show()

import pandas as pd
iris = pd.read_csv("/content/IRIS (1).csv")

x = iris.iloc[:,:-1].values
y = iris.iloc[:, -1].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3)
y_pred = kmeans.fit_predict(x)
# print(kmeans.cluster_centers_)

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x[y_pred == 0,0], x[y_pred == 0,1], x[y_pred == 0,2], s=50, c='red', label='Setosa')
ax.scatter(x[y_pred == 1,0], x[y_pred == 1,1], x[y_pred == 1,2], s=50, c='green', label='Versicolor')
ax.scatter(x[y_pred == 2,0], x[y_pred == 2,1], x[y_pred == 2,2], s=50, c='blue', label='Verginica')
ax.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], kmeans.cluster_centers_[:,2], s=150, c='yellow', label='Centroids')

plt.legend()
plt.show()

import pandas as pd
iris = pd.read_csv("/content/IRIS (1).csv")

x = iris.iloc[:,:-1].values
y = iris.iloc[:, -1].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters = 3)
y_pred = hc.fit_predict(x)
#print(kmeans.cluster_centers_)

import matplotlib.pyplot as plt
plt.scatter(x[kmeans == 0,0], x[kmeans == 0,1], s=50, c='red', label='Setosa')
plt.scatter(x[kmeans == 1,0], x[kmeans == 1,1], s=50, c='green', label='Versicolor')
plt.scatter(x[kmeans == 2,0], x[kmeans == 2,1], s=50, c='blue', label='Verginica')
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s=150, c='yellow', label='Centroids')

from scipy.cluster.hierarchy import dendrogram, linkage
dendrogram(linkage(x))
plt.show()